services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    networks:
      - ${NETWORK_NAME}
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    depends_on:
      - ollama
    restart: unless-stopped

networks:
  ci_network:
    external: true

volumes:
  ollama: {}
  open-webui: {}
