#!/bin/bash
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"
echo "hello from setup_bounty_1"

docker cp ../setup_files mlflow:/app
docker exec mlflow bash -c 'head -c 16 /dev/urandom | base64 | tr -d /+= | head -c 16 > /etc/FLAG.txt'