services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    networks:
      - shared_net
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/backend/data

networks:
  shared_net:
    external: true