services:
  gpt-academic:
    container_name: gpt-academic-app
    build: 
      context: ../../../  # Go up to access codebase
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
    ports:
      - "12345:12345"
    environment:
      - WEB_PORT=12345
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  shared_net:
    external: true