services:
  bentoml_service:
    container_name: bentoml-host
    build: 
      context: ../../../
      dockerfile: ./bounties/bounty_1/setup_files/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - shared_net
    volumes:
      - ./bento_logs:/bento_logs 
    command: >
      bash -c "bentoml serve . --port 3001 > /bento_logs/bento.log"

  flask_service:
    container_name: server-host
    build: 
      context: ../../../
      dockerfile: ./bounties/bounty_1/setup_files/server/Dockerfile
    ports:
      - "1234:1234"  
    networks:
      - shared_net
    volumes:
      - ./server_logs:/server_logs 
    command: >
      python3 server/app.py

networks:
  shared_net:
    external: true