services:
  neural_compressor:
    container_name: neural-compressor
    build: 
      context: ../../../
      dockerfile: ./bounties/bounty_0/setup_files/Dockerfile
    # command: ["neural_solution", "start", "--restful_api_port=8005", "--result_monitor_port=8006", "--task_monitor_port=8007", "--api_type=restful", "--conda_env=py_env"]
    volumes:
    # Persistent storage that will keep across runs
      - persistent_storage:/app/persistent
    ports:
      - "8005:8005"
      - "8006:8006"
      - "8007:8007"
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8005/\").read()' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - shared_net

networks:
  shared_net:
    external: true

volumes:
  persistent_storage:
    external: false