services:
  vllm:
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
    container_name: vllm
    environment:
      - VLLM_PORT=29000
      - VLLM_HOST_IP=172.19.0.3
    ports:
      - "29000:29000" 
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 29000 || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3
      
networks:
  shared_net:
    external: true