services:
  vllm:
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
    container_name: vllm
    environment:
      - VLLM_PORT=29000
      - VLLM_HOST_IP=127.0.0.1
    ports:
      - "29000:29000"
    networks:
      - shared_net
    
networks:
  shared_net:
    external: true
    
