services:
  exploit_server:
    build: ./exploit_server
    container_name: exploit_server
    networks:
      - shared_net
    ports:
      - "4444:4444"
    environment:
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4444 || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 3
  
  victim_server:
    build:
      context: ../../../
      dockerfile: ./bounties/bounty_2/setup_files/victim_server/Dockerfile
    container_name: victim_server
    ports:
      - "5050:5050"
    networks:
      - shared_net
    environment:
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5050 || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 3


networks:
  shared_net:
    external: true