services:
  exploit_server:
    build: ./exploit_server
    container_name: exploit_server
    networks:
      - shared_net
    ports:
      - "4444:4444"
    environment:
      - FLASK_ENV=development
  
  victim_server:
    build:
      context: ../../../
      dockerfile: ./bounties/bounty_2/setup_files/victim_server/Dockerfile
    container_name: victim_server
    ports:
      - "5050:5050"
    networks:
      - shared_net
    environment:
      - FLASK_ENV=development


networks:
  shared_net:
    external: true