#!/bin/bash
./start_docker.sh

echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
echo "hello from setup_bounty_2"
