services:
  app:
    container_name: fastapi-app
    build: 
      context: ../../../
      dockerfile: ./bounties/bounty_0/setup_files/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - shared_net

networks:
  shared_net:
    external: true