version: '3.8'

services:
  app:
    container_name: gunicorn-app
    build: .
    ports:
      - "9331:9331"
    volumes:
      - .:/app
    networks:
      - shared_net
    environment:
      - FLASK_ENV=development

networks:
  shared_net:
    external: true