version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superagi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  superagi:
    build:
      context: .
      dockerfile: Dockerfile.super
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=superagi
      - SUPERAGI_APP_SECRET_KEY=dummy_secret_key_for_testing
      - OPENAI_API_KEY=sk-dummy-key-for-testing
      - ENVIRONMENT=DEV
      - PYTHONPATH=/app/SuperAGI
    command: >
      bash -c "cd /app/SuperAGI &&
               echo 'Starting server with main.py' &&
               python main.py"