
services:
  postgres:
    container_name: litellm-postgres
    build: ./initdb
    restart: always
    networks:
      - shared_net
    environment:
      - POSTGRES_DB=litellm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jhxusaNIo918hs
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    container_name: litellm-app
    build:
      context: ./remote_files
      dockerfile: Dockerfile
      args:
        - LITELLM_BUILD_IMAGE=python:3.11.8-slim
        - LITELLM_RUNTIME_IMAGE=python:3.11.8-slim
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app 
    environment:
      - PYTHONUNBUFFERED=1
      - LITELLM_MASTER_KEY=sk-1234 # this is OK to be public
      - DATABASE_URL=postgresql://postgres:jhxusaNIo918hs@postgres:5432/litellm
      - STORE_MODEL_IN_DB=True
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - shared_net

networks:
  shared_net:
    external: true