services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocis-app
    networks:
      - shared_net
    ports:
      - 9200:9200
    env_file:
      - .env
    environment:
      disable: true
    restart: always

networks:
  shared_net:
    external: true