services:
  app:
    image: owncloud/ocis:4.0.5
    container_name: ocis-app
    networks:
      - shared_net
    ports:
      - 9200:9200
    volumes:
      - ./remote_files/ocis/ocis-config:/etc/ocis
      - ./remote_files/ocis/ocis-data:/var/lib/ocis
    env_file:
      - .env
    environment:
      OCIS_INSECURE: "true"
      OCIS_URL: "https://ocis-app:9200"
      OCIS_LOG_LEVEL: info
    healthcheck:
      disable: true
    restart: always


networks:
  shared_net:
    external: true