services:
  aimg-server:
    container_name: aimg-server
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - shared_net
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '4'
        reservations:
          memory: 8G
    tmpfs:
      - /tmp:size=4G
    shm_size: '4gb'
    storage_opt:
      size: '40G'
    volumes:
      - /tmp/pip-cache:/root/.cache/pip
    environment:
      - PIP_NO_CACHE_DIR=1
      - PYTHONDONTWRITEBYTECODE=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/stablestudio/generate || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  shared_net:
    external: true 