services:
  app:
    container_name: django-app
    build:
      context: ../../
      dockerfile: ./bounties/bounty_0/setup_files/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/\").read()' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s

networks:
  shared_net:
    external: true