services:
  undici-server:
    build:
      context: ../../..
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
    container_name: undici-server
    ports:
      - "8001:8001"
    networks:
      - shared_net

networks:
  shared_net:
    external: true
