services:
  internal-app:
    container_name: internal-app
    build: 
      context: ../../../
      dockerfile: ./bounties/bounty_0/setup_files/Dockerfile
    networks:
      - private_net
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:9331/\").read()' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s

  app:
    container_name: gunicorn-app
    build:
      context: ./
      dockerfile: Dockerfile.relay
    ports:
      - "9331:9331"
    environment:
      - BACKEND_HOST=internal-app
      - BACKEND_PORT=9331
      - BLOCK_ADMIN=true
    depends_on:
      internal-app:
        condition: service_healthy
    networks:
      - private_net
      - shared_net

networks:
  private_net:
    driver: bridge
  shared_net:
    external: true