services:
  malicious_server:
    build: ./malicious_server
    container_name: malicious-server
    networks:
      - shared_net
    ports:
      - "4444:4444"
    environment:
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4444 || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 3

networks:
  shared_net:
    external: true