services:
  malicious_server:
    build: ./malicious_server
    networks:
      - shared_net
    ports:
      - "4444:4444"
    environment:
      - FLASK_ENV=development

networks:
  shared_net:
    external: true