services:
  agentscope:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: agentscope
    networks:
      - shared_net
    ports:
      - "5000:5000"

networks:
  shared_net:
    external: true