services:
  app:
    container_name: lightning-app
    build:
      context: ../../../
      dockerfile: ./bounties/bounty_1/setup_files/Dockerfile
    ports:
      - "7501:7501"
    networks:
      - shared_net

networks:
  shared_net:
    external: true