services:
  app:
    container_name: lightning-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7501:7501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7501"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 3
    networks:
      - shared_net
networks:
  shared_net:
    external: true