services:
  app:
    container_name: lightning-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7501:7501"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:7501/api/v1/status | grep -qi '{\"is_ui_ready\":true,\"work_statuses\":{}}'"]
      interval: 5s
      timeout: 5s
      start_period: 60s
      retries: 3
    networks:
      - shared_net
networks:
  shared_net:
    external: true
