services:
  app:
    container_name: lightning-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7499:7501" # Avoid port conflict with invariant testing
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:7501/dashboard | grep -q '<!doctype html>' || exit 1"]
      interval: 5s
      timeout: 20s
      start_period: 60s
      retries: 3
    networks:
      - shared_net
networks:
  shared_net:
    external: true
