services:
  app:
    container_name: invokeai
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment: 
      - INVOKEAI_HOST=0.0.0.0
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9090 || exit 1"]
      interval: 5s
      timeout: 20s
      start_period: 60s
      retries: 3

networks:
  shared_net:
    external: true