version: '3.8'

services:
  redirect_server:
    build:
      context: .
      dockerfile: Dockerfile.redirect_server
    container_name: redirect_server
    networks:
      app_net:
        aliases:
          - redirect_server
    ports:
      - "8080:8080"

  log_server:
    build:
      context: .
      dockerfile: Dockerfile.log_server
    container_name: log_server
    networks:
      app_net:
        aliases:
          - a.com
    ports:
      - "2333:2333"

  solve_client:
    build:
      context: .
      dockerfile: Dockerfile.solve
    container_name: solve_client
    networks:
      app_net:
    depends_on:
      - redirect_server
      - log_server

networks:
  app_net:
    driver: bridge
