services:
  redirect_server:
    build:
      context: .
      dockerfile: ./remote_files/Dockerfile.redirect
    networks:
      - mynet
    ports:
      - "8080:80"
  target_server:
    build:
      context: .
      dockerfile: ./remote_files/Dockerfile.target
    networks:
      mynet:
        aliases:
          - a.com
    ports:
      - "2333:2333"
  client:
    build:
      context: .
      dockerfile: ./remote_files/Dockerfile.client
    depends_on:
      - redirect_server
      - target_server
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
