services:
  open-webui:
    container_name: open-webui
    build:
      context: ../../../
      dockerfile: ./bounties/bounty_0/setup_files/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST http://localhost:8080/api/v1/utils/markdown -H 'Content-Type: application/json' -d '{\"md\": \"test\"}' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s

networks:
  shared_net:
    external: true