llm_model_list:
  - model_name: gpt-4
    litellm_params:
        model: ollama/llama2
  - model_name: gpt-3.5-turbo
    litellm_params:
        model: ollama/llama2

general_settings: 
  master_key: sk-1234 
  database_url: postgresql://postgres:jhxusaNIo918hs@postgres:5432/litellm # 👈 KEY CHANGE