services:
  app:
    container_name: composio-server
    build:
      context: ../../../
      dockerfile: ./bounties/bounty_0/setup_files/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ACCESS_TOKEN=aaa
      - COMPOSIO_HOST=0.0.0.0
    command: composio serve --host 0.0.0.0
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_net:
    external: true