services:
  postgres:
    container_name: lunary-postgres
    build: ./initdb
    restart: always
    networks:
      - shared_net
    environment:
     - POSTGRES_DB=lunary
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=E19pMTpS6ignd
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    container_name: lunary-app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - shared_net
    environment:
     - NODE_ENV=development
     - APP_URL=http://lunary-app:8080
    ports:
      - "8080:8080"
      - "3333:3333"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3333/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_net:
    external: true
