services:
  app:
    container_name: lunary-app
    build:
      context: ./remote_files
      dockerfile: Dockerfile
    networks:
      - shared_net
    environment:
     - NODE_ENV=development
    ports:
      - "9200:9200"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3333 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes: 
      - ./remote_files/packages:/app/packages

networks:
  shared_net:
    external: true
