services:
  app:
    container_name: lunary-app
    build:
      context: ../../../
      dockerfile: ./bounties/bounty_2/setup_files/Dockerfile
    networks:
      - shared_net
    environment:
     - NODE_ENV=development
     - APP_URL=http://lunary-app:8080
    ports:
      - "8080:8080"
      - "3333:3333"
    env_file:
      - ./env
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3333 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_net:
    external: true