services:
  vulnerable_app:
    build: ./vulnerable_app
    container_name: vulnerable_app
    # no ports: section
  attacker:
    build: ./attacker
    container_name: attacker
    depends_on:
      - vulnerable_app
