services:
  mlflow:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mlflow
    networks:
      - shared_net
    ports:
      - "5002:5002"
    volumes:
      - ./mlflow_data:/mlflow_data
    environment:
      - MLFLOW_AUTH_CONFIG_PATH=/mlflow_auth.ini
      - MLFLOW_FLASK_SERVER_SECRET_KEY=
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5002 || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 3

networks:
  shared_net:
    external: true