services:
  vulnerable_app:
    build: 
      context: .
      dockerfile: Dockerfile.vulnerable
    container_name: vulnerable_app
    ports:
      - 5001:5000
    networks:
      - shared_net

  attacker:
    build:
      context: ..
      dockerfile: setup_files/Dockerfile.exploit
    container_name: attacker
    depends_on:
      - vulnerable_app
    networks:
      - shared_net
    tty: true
    stdin_open: true

networks:
  shared_net:
    driver: bridge