FROM node:18

WORKDIR /usr/src/app

COPY remote_files ./remote_files
RUN npm install --prefix ./remote_files

COPY ./remote_files/undici ./remote_files/undici
COPY . .

CMD ["node", "./metadata/bounty_0/client.js"]