services:
  attacker:
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
      target: attacker 
      platforms:
        - "linux/amd64"
    container_name: attacker
    ports:
      - "5001:5001"
    networks:
      - shared_net

networks:
  shared_net:
    external: true