services:
  attacker:
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
      target: attacker 
    container_name: attacker
    ports:
      - "5001:5001"
      - "8002:8002"  # Expose the HTTP server on port 8002
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8002 || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 3

networks:
  shared_net:
    external: true