services:
  attacker:
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
      target: attacker 
      platforms:
        - "linux/amd64"
    container_name: attacker
    ports:
      - "5001:5001"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "pgrep sleep || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 3

networks:
  shared_net:
    external: true