name: Check pytest tests
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch --depth=1 origin main:refs/remotes/origin/main

      - name: Setup Python environment
        uses: actions/setup-python@v5

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt

      - name: Docker Cleanup before pulling new image
        run: |
          docker system prune -af
          docker image prune -af

      - name: Pull Docker Container
        run: |
          docker pull cybench/kali-linux-ci:latest
          docker manifest inspect cybench/kali-linux-ci:latest
          docker image tag cybench/kali-linux-ci:latest cybench

      - name: Display disk space after pulling image
        run: df -H

      - name: Create Docker Network
        run: docker network create shared_net || true

      - name: Find modified metadata/bounty directories
        id: modified-dirs
        run: |
          cat << 'EOF' > /tmp/shared_functions.sh
          execute_if_exists() {
            local script_path="$1"
            if [ -f "$script_path" ]; then
              echo "Executing $script_path"
              bash "$script_path"
            else
              echo "$script_path not found, skipping."
            fi
          }

          get_modified_dirs() {
            git diff --diff-filter=ACM --name-only origin/main...HEAD | grep 'metadata/bounty' | tr '\n' '\0' | xargs -0 -n1 dirname | sed -E "s/(.*\/metadata\/bounty_[0-9]+).*/\1/" | sort -u
          }
          EOF
          chmod +x /tmp/shared_functions.sh
          source /tmp/shared_functions.sh
          modified_dirs=$(get_modified_dirs)
          echo "modified_dirs<<EOF" >> $GITHUB_OUTPUT
          echo "$modified_dirs" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Exploit Tests
        if: steps.modified-dirs.outputs.modified_dirs != ''
        run: |
          source /tmp/shared_functions.sh
          echo "${{ steps.modified-dirs.outputs.modified_dirs }}" | while read -r dir; do
            task_dir=$(dirname "$(dirname "$dir")")
            echo "Processing bug bounty: $dir"

            # Start Docker for this bug bounty
            echo "Starting Docker for $task_dir"
            execute_if_exists "$task_dir/start_docker.sh"

            # Run the exploit and verification for this task
            echo "Running exploit and verification test for $dir"
            pytest --log-cli-level=INFO tests/exploit_test.py::test_exploit_script --dirs "$dir"

            # Stop Docker for this task
            echo "Stopping Docker for $task_dir"
            execute_if_exists "$task_dir/stop_docker.sh"

            echo "Completed processing bug bounty: $dir"
            echo "-----------------------------------"
          done
          echo "All tasks processed."

      - name: Run Fix Tests
        if: steps.modified-dirs.outputs.modified_dirs != ''
        run: |
          source /tmp/shared_functions.sh
          echo "${{ steps.modified-dirs.outputs.modified_dirs }}" | while read -r dir; do
            task_dir=$(dirname "$(dirname "$dir")")
            echo "Processing bug bounty: $dir"

            # Fix the bug for this task
            bounty_metadata="$dir/bounty_metadata.json"

            fix_pairs=$(jq -r '.fix | to_entries[] | "\(.key) \(.value)"' "$bounty_metadata")

            # Apply the fixes by copying local files to their target locations
            declare -A original_files
            echo "Applying fixes for $dir"
            while read -r source_file target_file; do
              # Ensure the target directory exists
              target_dir=$(dirname "$target_file")
              if [ ! -d "$task_dir/$target_dir" ]; then
                echo "Creating directory $task_dir/$target_dir"
                mkdir -p "$task_dir/$target_dir"
              fi

              # Store the original file to restore later
              original_files["$task_dir/$target_file"]=$(mktemp)
              if [ -f "$task_dir/$target_file" ]; then
                cp "$task_dir/$target_file" "${original_files["$task_dir/$target_file"]}"
              fi

              # Apply the fix by copying the source file to the target location
              echo "Copying $task_dir/$source_file to $task_dir/$target_file"
              cp "$task_dir/$source_file" "$task_dir/$target_file"
            done <<< "$fix_pairs"

            # Start Docker for this task after fix
            echo "Starting Docker for $task_dir"
            execute_if_exists "$task_dir/start_docker.sh"

            # Run the fix test for this task
            echo "Running fix test for $dir"
            pytest --log-cli-level=INFO tests/fix_test.py::test_exploit_script --dirs "$dir"

            # Stop Docker for this task
            echo "Stopping Docker for $task_dir"
            execute_if_exists "$task_dir/stop_docker.sh"

            # Restore the original files after testing
            echo "Restoring original files for $dir"
            for target_file in "${!original_files[@]}"; do
              echo "Restoring $target_file"
              mv "${original_files["$target_file"]}" "$target_file"
            done

            echo "Completed processing bug bounty: $dir"
            echo "-----------------------------------"
          done
          echo "All tasks processed."

      - name: Test init_script.sh
        run: |
          modified_files=$(git diff --diff-filter=ACM --name-only origin/main...HEAD | grep '.*/init_script.sh$' || true)
          if [ -z "$modified_files" ]; then
            echo "No init_script.sh diff found."
            exit 0
          fi
          echo "Modified init_script paths: $modified_files"
          modified_dirs=$(echo "$modified_files" | tr '\n' '\0' | xargs -0 -n1 dirname | sed -E "s/(.*\/benchmark\/.*)\/.*/\1/" | sort -u)
          echo "$modified_dirs" | tr '\n' '\0' | xargs -0 pytest --log-cli-level=INFO tests/init_script_test.py::test_modified_init_script --dirs
          echo "Directories to be tested: $modified_dirs"

      - name: Test project metadata.json
        run: |
          modified_files=$(git diff --diff-filter=ACM --name-only origin/main...HEAD | grep '.*/metadata/metadata.json$' || true)
          if [ -z "$modified_files" ]; then
            echo "No relevant files in metadata were modified."
            exit 0  # Exit successfully if no files are modified
          fi
          echo "Modified metadata.json files: $modified_files"
          modified_dirs=$(echo "$modified_files" | tr "\n" "\0" | xargs -0 -n1 dirname | sort -u)
          echo "$modified_dirs" | tr '\n' '\0' | xargs -0 pytest --log-cli-level=INFO tests/metadata_json_test.py::test_project_metadata --dirs
          echo "Directories to be tested: $modified_dirs"
        
      - name: Test bounty metadata.json
        run: |
          modified_files=$(git diff --diff-filter=ACM --name-only origin/main...HEAD | grep '.*/metadata/.*/bounty_metadata.json$' || true)
          if [ -z "$modified_files" ]; then
            echo "No relevant files in bounty metadata were modified."
            exit 0  # Exit successfully if no files are modified
          fi
          echo "Modified bounty_metadata.json files: $modified_files"
          modified_dirs=$(echo "$modified_files" | tr "\n" "\0" | xargs -0 -n1 dirname | sort -u)
          echo "$modified_dirs" | tr '\n' '\0' | xargs -0 pytest --log-cli-level=INFO tests/metadata_json_test.py::test_bounty_metadata --dirs
          echo "Directories to be tested: $modified_dirs"

      - name: Display disk space after tests
        run: df -h

      - name: Docker Cleanup after tests
        run: |
          docker system prune -af

      - name: Display disk space after cleanup
        run: df -h
