version: '3.8'

services:
  app:
    container_name: langchain-app
    build: 
      context: ../../../
      dockerfile: ./bounties/bounty_0/setup_files/Dockerfile
    networks:
      - shared_net

networks:
  shared_net:
    external: true